return {
 ["LatinModernRoman#655360"]={ "lmroman10-regular.otf", false },
 ["LatinModernRoman/B#b#655360"]={ "lmroman10-bold.otf", false },
 ["LatinModernRoman/B:mode=node;script=latn;language=DFLT;+tlig;#b#655360"]={ "lmroman10-bold.otf", false },
 ["LatinModernRoman/BI#bi#655360"]={ "lmroman10-bolditalic.otf", false },
 ["LatinModernRoman/I#i#655360"]={ "lmroman10-italic.otf", false },
 ["LatinModernRoman/I:mode=node;script=latn;language=DFLT;+tlig;#i#655360"]={ "lmroman10-italic.otf", false },
 ["LatinModernRoman:mode=node;script=latn;language=DFLT;+tlig;#655360"]={ "lmroman10-regular.otf", false },
 ["NotoSerif#655360"]={ "NotoSerif-Regular.ttf", false },
 ["NotoSerif/B#b#655360"]={ "NotoSerif-Bold.ttf", false },
 ["NotoSerif/B:mode=node;script=latn;language=DFLT;+tlig;#b#655360"]={ "NotoSerif-Bold.ttf", false },
 ["NotoSerif/B:mode=node;script=latn;language=DFLT;+tlig;#b#786432"]={ "NotoSerif-Bold.ttf", false },
 ["NotoSerif/B:mode=node;script=latn;language=DFLT;+tlig;#b#943718"]={ "NotoSerif-Bold.ttf", false },
 ["NotoSerif/BI#bi#655360"]={ "NotoSerif-BoldItalic.ttf", false },
 ["NotoSerif/I#i#655360"]={ "NotoSerif-Italic.ttf", false },
 ["NotoSerif/I:mode=node;script=latn;language=DFLT;+tlig;#i#655360"]={ "NotoSerif-Italic.ttf", false },
 ["NotoSerif:mode=node;script=latn;language=DFLT;+tlig;#1132462"]={ "NotoSerif-Regular.ttf", false },
 ["NotoSerif:mode=node;script=latn;language=DFLT;+tlig;#327680"]={ "NotoSerif-Regular.ttf", false },
 ["NotoSerif:mode=node;script=latn;language=DFLT;+tlig;#393216"]={ "NotoSerif-Regular.ttf", false },
 ["NotoSerif:mode=node;script=latn;language=DFLT;+tlig;#458752"]={ "NotoSerif-Regular.ttf", false },
 ["NotoSerif:mode=node;script=latn;language=DFLT;+tlig;#524288"]={ "NotoSerif-Regular.ttf", false },
 ["NotoSerif:mode=node;script=latn;language=DFLT;+tlig;#655360"]={ "NotoSerif-Regular.ttf", false },
 ["NotoSerif:mode=node;script=latn;language=DFLT;+tlig;#786432"]={ "NotoSerif-Regular.ttf", false },
 ["NotoSerif:mode=node;script=latn;language=DFLT;+tlig;#943718"]={ "NotoSerif-Regular.ttf", false },
}
